[img]
img_input_dir = "data/raw_jpg"
img_output_dir = "data/processed"
result_output_dir = "data/dataset"
result_csv_path = "data/dataset/total_dataset.csv"
plot_output_dir = "data/plot"
save_processed_images = false
save_processed_data = true

[data]
hole_pt = [192, 150]
tip_pt = [192, 30]
distance_scale = 0.33e-3  # 1 px = 1/3 mm
time_scale =10e-6   # 1 frame = 10 \mu s

[plot]
frame_stride = 50
